# Generated by Django 3.0.6 on 2020-05-14 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(blank=True)),
                ('msg_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('is_contacted', models.BooleanField(blank=True, default=False)),
                ('contact_date', models.DateTimeField(blank=True)),
                ('contact_outcome', models.TextField(blank=True)),
                ('is_contracted', models.BooleanField(blank=True, default=False)),
                ('contract_date', models.DateTimeField(blank=True)),
                ('contract_details', models.TextField(blank=True)),
                ('is_ok', models.BooleanField(blank=True)),
                ('contact_details', models.TextField(blank=True)),
            ],
        ),
    ]
