# Generated by Django 3.0.6 on 2020-05-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20200514_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='browser_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='browser_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='device_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='os_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='os_version',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
